#!/usr/bin/env node
// Scaffold the EduTools course tree (javascript/ and typescript/ tracks) from
// tools/curriculum.json. Writes section-info.yaml, lesson-info.yaml, and a stub
// task-info.yaml + task.md per stage. Idempotent and safe:
//   - drops a `.scaffold-generated` marker in every lesson dir it creates
//   - never overwrites a lesson dir that carries a hand-dropped `.populated` marker
//   - `--clean` removes only generated-only lesson dirs before regenerating
//   - `--dry-run` prints the plan and writes nothing
//
// This is an authoring tool (Node, no dependencies). It is the CAP/Node port of the
// Python reference course's scaffold_course.py. See docs/AUTHORING_NOTES.md.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const MANIFEST = path.join(ROOT, "tools", "curriculum.json");
const TRACKS = ["javascript", "typescript"];

const args = process.argv.slice(2);
const DRY = args.includes("--dry-run");
const CLEAN = args.includes("--clean");

const pad2 = (n) => String(n).padStart(2, "0");
const rel = (p) => path.relative(ROOT, p) || ".";
const q = (s) => JSON.stringify(String(s)); // valid double-quoted YAML scalar (single line)

function ensureDir(d) {
  if (!DRY) fs.mkdirSync(d, { recursive: true });
}
function writeFile(file, content) {
  if (DRY) {
    console.log("  would write", rel(file));
    return;
  }
  ensureDir(path.dirname(file));
  fs.writeFileSync(file, content);
  console.log("  wrote", rel(file));
}

// A lesson is an EduTools framework lesson (code carries forward) only if none of its
// stages are theory/choice — those render blank inside a framework lesson.
function isFramework(lesson) {
  const types = (lesson.tasks || []).map((t) => t.task_type || "edu");
  return types.length > 0 && !types.some((t) => t === "theory" || t === "choice");
}

function lessonsForTrack(manifest, track) {
  const phaseLessons = manifest.phases.flatMap((p) => p.lessons);
  const numbered = phaseLessons.map((l, i) => ({ ...l, nn: pad2(i + 1) }));
  if (track === "typescript" && manifest.typescript_prologue) {
    return [{ ...manifest.typescript_prologue, nn: "00" }, ...numbered];
  }
  return numbered;
}

function lessonInfoYaml(lesson, taskDirNames) {
  const lines = [];
  if (isFramework(lesson)) {
    lines.push("type: framework");
  }
  lines.push(`custom_name: ${q(lesson.title)}`);
  lines.push("content:");
  for (const t of taskDirNames) lines.push(`  - ${t}`);
  if (isFramework(lesson)) lines.push("is_template_based: false");
  return lines.join("\n") + "\n";
}

function taskInfoYaml(task) {
  const type = task.task_type || "edu";
  const lines = [`type: ${type}`];
  if (task.title) lines.push(`custom_name: ${q(task.title)}`);
  lines.push("files:");
  if (type === "theory" || type === "choice" || type === "output") {
    lines.push("  - name: task.md");
    lines.push("    visible: true");
    if (type === "output") {
      lines.push("  - name: solution.js");
      lines.push("    visible: true");
    }
  } else {
    // edu stub. Real edu stages are authored as <file>.tmpl and have their task-info
    // regenerated by build-placeholders.mjs; this is only a loadable placeholder.
    lines.push("  - name: solution.js");
    lines.push("    visible: true");
    lines.push("  - name: test/test.js");
    lines.push("    visible: false");
    lines.push("    propagatable: false");
  }
  return lines.join("\n") + "\n";
}

function taskMd(lesson, task) {
  const title = task.title || lesson.title;
  const summary = task.summary || lesson.summary || "";
  const features = task.cap_features || lesson.cap_features || [];
  let md = `# ${title}\n\n${summary}\n`;
  if (features.length) {
    md += "\n## What this lesson covers\n\n";
    md += features.map((f) => `- ${f}`).join("\n") + "\n";
  }
  md +=
    "\n_Overview stage. The hands-on stages for this lesson are authored during course " +
    "population — see CLAUDE.md (B11) and docs/AUTHORING_NOTES.md._\n";
  return md;
}

function eduStubFiles(taskDir) {
  writeFile(
    path.join(taskDir, "solution.js"),
    "// TODO(author): replace with the real starter, authored as <file>.tmpl\n" +
      "// then run: node tools/build-placeholders.mjs <this stage dir>\n"
  );
  writeFile(
    path.join(taskDir, "test", "test.js"),
    'describe("stage (not authored yet)", () => {\n' +
      '  it.skip("replace with real checks (validity, not conformity)", () => {});\n' +
      "});\n"
  );
}

function cleanTrack(trackDir) {
  if (!fs.existsSync(trackDir)) return;
  for (const name of fs.readdirSync(trackDir)) {
    const dir = path.join(trackDir, name);
    if (!fs.statSync(dir).isDirectory()) continue;
    const generated = fs.existsSync(path.join(dir, ".scaffold-generated"));
    const populated = fs.existsSync(path.join(dir, ".populated"));
    if (generated && !populated) {
      console.log("  clean", rel(dir));
      if (!DRY) fs.rmSync(dir, { recursive: true, force: true });
    }
  }
}

function main() {
  const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));
  console.log(`Scaffolding "${manifest.capstone}" (${DRY ? "dry-run" : "writing"}${CLEAN ? ", clean" : ""})`);

  for (const track of TRACKS) {
    const trackDir = path.join(ROOT, track);
    console.log(`\n[${track}]`);
    if (CLEAN) cleanTrack(trackDir);
    ensureDir(trackDir);

    const lessons = lessonsForTrack(manifest, track);
    const lessonDirNames = [];

    for (const lesson of lessons) {
      const lessonDirName = `${lesson.nn}-${lesson.slug}`;
      lessonDirNames.push(lessonDirName);
      const lessonDir = path.join(trackDir, lessonDirName);

      if (fs.existsSync(path.join(lessonDir, ".populated"))) {
        console.log("  keep (populated)", rel(lessonDir));
        continue;
      }

      const tasks = lesson.tasks && lesson.tasks.length ? lesson.tasks : [{ slug: "overview", title: "Overview and roadmap", task_type: "theory" }];
      const taskDirNames = [];
      ensureDir(lessonDir);

      tasks.forEach((task, i) => {
        const taskDirName = `s${pad2(i + 1)}-${task.slug}`;
        taskDirNames.push(taskDirName);
        const taskDir = path.join(lessonDir, taskDirName);
        ensureDir(taskDir);
        writeFile(path.join(taskDir, "task-info.yaml"), taskInfoYaml(task));
        writeFile(path.join(taskDir, "task.md"), taskMd(lesson, task));
        if ((task.task_type || "edu") === "edu") eduStubFiles(taskDir);
      });

      writeFile(path.join(lessonDir, "lesson-info.yaml"), lessonInfoYaml(lesson, taskDirNames));
      if (!DRY) fs.writeFileSync(path.join(lessonDir, ".scaffold-generated"), "generated by tools/scaffold-course.mjs\n");
    }

    // section-info.yaml lists the track's lessons in order.
    const sectionLines = ["content:", ...lessonDirNames.map((n) => `  - ${n}`)];
    writeFile(path.join(trackDir, "section-info.yaml"), sectionLines.join("\n") + "\n");
  }

  console.log("\nDone.");
}

main();
